const allSQL = [
    // "INSERT INTO `users` (name,email,photoURL,password) VALUES (?,?,?,?)",
    // "INSERT INTO `users` (type,name,email,photoURL,password) VALUES (?,?,?,?,?)",
    // "SELECT user_id, type, name, email, photoURL FROM `users` where `users`.`email` = ? AND `users`.`password` = ? AND `users`.`type` != 'googleuser'",
    // 'SELECT user_id, type, name, email, photoURL FROM `users` where `users`.`email` = ?',
    // 'INSERT INTO `posts` (publisher_id, time, description, image, video) VALUES (?,?,?,?,?)',
    // "SELECT * FROM `posts` JOIN `users` ON `posts`.`publisher_id` = `users`.`user_id` ORDER BY `posts`.`time` DESC",
    // "SELECT COUNT(*) AS 'likes' FROM `likes` WHERE `likes`.`post_id` = ?",
    // "SELECT COUNT(*) AS 'comments' FROM `comments` WHERE `comments`.`post_id` = ?",
    // "SELECT COUNT(*) AS 'shares' FROM `shares` WHERE `shares`.`post_id` = ?",
    // "SELECT * FROM `likes` WHERE `likes`.`post_id` = ? AND `likes`.`liker_id` = ?",
    // "INSERT INTO `likes` (post_id,liker_id) VALUES (?,?)",
    // "INSERT INTO `comments` (post_id,commenter_id,content) VALUES (?,?,?)",
    // "INSERT INTO `shares` (post_id,sharer_id) VALUES (?,?)",
    // 'SELECT * FROM `comments` JOIN `users` ON `comments`.`commenter_id` = `users`.`user_id` WHERE `comments`.`post_id` = ?',
    'INSERT INTO `shop_products` (product_name, description,price,image) VALUES (?,?,?,?)',
    'SELECT * FROM `shop_products`',
    'INSERT INTO `market_products` (seller_id, product_name, description,time,price,image) VALUES (?,?,?,?,?,?)',
    'SELECT * FROM `market_products` JOIN `users` ON `market_products`.`seller_id` = `users`.`user_id`',
    'SELECT * FROM `posts` WHERE `posts`.`publisher_id` = ? ORDER BY `time` DESC',
    'SELECT * FROM `market_products` WHERE `market_products`.`seller_id` = ? ORDER BY `time` DESC',
    'SELECT * FROM `shop_products`',
    "SELECT * from `shop_products` WHERE `shop_products`.`product_name` LIKE '%"+ input + "%'",
    "SELECT * from `market_products` WHERE `market_products`.`product_name` LIKE '%"+ input + "%'",
    'INSERT INTO `advertisement` (name,image,link) VALUES (?,?,?)',
    'SELECT * FROM `advertisement`',
    'INSERT INTO `shop_cart` (product_id,user_id) VALUES (?,?)',
    'SELECT * FROM `shop_cart` JOIN `shop_products` ON `shop_cart`.`product_id` = `shop_products`.`product_id` WHERE `shop_cart`.`user_id` = ?',
    'INSERT INTO `market_cart` (user_id, product_id) VALUES (?,?)',
    'SELECT * FROM `market_cart` JOIN `market_products` ON `market_cart`.`product_id` = `market_products`.`market_id` WHERE `market_cart`.`user_id` = ?',
    "DELETE FROM `shop_cart` WHERE `shop_cart`.`user_id` = ? ;",
    "INSERT INTO bills (user_id, date, type) VALUES (" + String(userId) + "," + "'" + time + "'" + ",0);",
    "SELECT LAST_INSERT_ID(bill_id) FROM `bills` ORDER BY `bills`.`bill_id` DESC LIMIT 1",
    "DELETE FROM `market_cart` WHERE `market_cart`.`user_id` = ? ;",
    "INSERT INTO bills (user_id, date, type) VALUES (" + String(userId) + "," + "'" + time + "'" + ",1);",
    "SELECT LAST_INSERT_ID(bill_id) FROM `bills` ORDER BY `bills`.`bill_id` DESC LIMIT 1",
    "INSERT INTO shop_order (buyer_id, product_id, bill_id) VALUES (" + String(userId) + "," + String(shopCart[i].product_id) + "," + String(billId) + ");\n",
    "INSERT INTO market_order (buyer_id, seller_id, product_id, bill_id) VALUES (" + String(userId)+ "," + String(marketCart[i].seller_id) + "," + String(marketCart[i].market_id) + "," + String(billId) + ");\n",
    'SELECT * FROM `shop_order` JOIN `shop_products` ON `shop_order`.`product_id` = `shop_products`.`product_id` ORDER BY `shop_order`.`buyer_id`',
    'SELECT * FROM `market_order` JOIN `market_products` ON `market_order`.`product_id` = `market_products`.`market_id` WHERE `market_order`.`seller_id` = ? ORDER BY `market_order`.`buyer_id`',
    'SELECT name, email, photoURL FROM `users` WHERE `users`.`user_id` = ?',
    "SELECT * FROM `bills` WHERE `bills`.`user_id` = ? ORDER BY `bills`.`date` DESC",
    'SELECT * FROM `shop_order` JOIN `shop_products` ON `shop_order`.`product_id` = `shop_products`.`product_id` WHERE `shop_order`.`bill_id` = ?',
    'SELECT * FROM `market_order` JOIN `market_products` ON `market_order`.`product_id` = `market_products`.`market_id` WHERE `market_order`.`bill_id` = ?',
    'DELETE FROM `shop_products` WHERE `shop_products`.`product_id` = ?',
    'UPDATE `shop_products` SET `product_name` = ?, `description` = ?, `price` = ?, `image` = ? WHERE `shop_products`.`product_id` = ?',
    'DELETE FROM `market_products` WHERE `market_products`.`market_id` = ?',
    'UPDATE `market_products` SET `product_name` = ?, `description` = ?, `price` = ?, `image` = ? WHERE `market_products`.`market_id` = ?',
]

const allNoSQL = [
    
]